// Code generated by protoc-gen-go. DO NOT EDIT.
// source: higherlower/higherLower.proto

package higherlower

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GuessResponse_Result int32

const (
	GuessResponse_RESULT_UNSPECIFIED GuessResponse_Result = 0
	GuessResponse_HIGHER             GuessResponse_Result = 1
	GuessResponse_LOWER              GuessResponse_Result = 2
	GuessResponse_CORRECT            GuessResponse_Result = 3
)

var GuessResponse_Result_name = map[int32]string{
	0: "RESULT_UNSPECIFIED",
	1: "HIGHER",
	2: "LOWER",
	3: "CORRECT",
}

var GuessResponse_Result_value = map[string]int32{
	"RESULT_UNSPECIFIED": 0,
	"HIGHER":             1,
	"LOWER":              2,
	"CORRECT":            3,
}

func (x GuessResponse_Result) String() string {
	return proto.EnumName(GuessResponse_Result_name, int32(x))
}

func (GuessResponse_Result) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d764e6f5f232c7bd, []int{1, 0}
}

type GuessRequest struct {
	Guess                int32    `protobuf:"varint,1,opt,name=guess,proto3" json:"guess,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GuessRequest) Reset()         { *m = GuessRequest{} }
func (m *GuessRequest) String() string { return proto.CompactTextString(m) }
func (*GuessRequest) ProtoMessage()    {}
func (*GuessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d764e6f5f232c7bd, []int{0}
}

func (m *GuessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuessRequest.Unmarshal(m, b)
}
func (m *GuessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuessRequest.Marshal(b, m, deterministic)
}
func (m *GuessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuessRequest.Merge(m, src)
}
func (m *GuessRequest) XXX_Size() int {
	return xxx_messageInfo_GuessRequest.Size(m)
}
func (m *GuessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GuessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GuessRequest proto.InternalMessageInfo

func (m *GuessRequest) GetGuess() int32 {
	if m != nil {
		return m.Guess
	}
	return 0
}

type GuessResponse struct {
	Result               GuessResponse_Result `protobuf:"varint,1,opt,name=result,proto3,enum=higherlower.GuessResponse_Result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GuessResponse) Reset()         { *m = GuessResponse{} }
func (m *GuessResponse) String() string { return proto.CompactTextString(m) }
func (*GuessResponse) ProtoMessage()    {}
func (*GuessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d764e6f5f232c7bd, []int{1}
}

func (m *GuessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GuessResponse.Unmarshal(m, b)
}
func (m *GuessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GuessResponse.Marshal(b, m, deterministic)
}
func (m *GuessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuessResponse.Merge(m, src)
}
func (m *GuessResponse) XXX_Size() int {
	return xxx_messageInfo_GuessResponse.Size(m)
}
func (m *GuessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GuessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GuessResponse proto.InternalMessageInfo

func (m *GuessResponse) GetResult() GuessResponse_Result {
	if m != nil {
		return m.Result
	}
	return GuessResponse_RESULT_UNSPECIFIED
}

type Game struct {
	GameId               string   `protobuf:"bytes,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Answer               int32    `protobuf:"varint,2,opt,name=answer,proto3" json:"answer,omitempty"`
	Ended                bool     `protobuf:"varint,3,opt,name=ended,proto3" json:"ended,omitempty"`
	Result               string   `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Min                  int32    `protobuf:"varint,5,opt,name=min,proto3" json:"min,omitempty"`
	Max                  int32    `protobuf:"varint,6,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}
func (*Game) Descriptor() ([]byte, []int) {
	return fileDescriptor_d764e6f5f232c7bd, []int{2}
}

func (m *Game) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game.Unmarshal(m, b)
}
func (m *Game) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game.Marshal(b, m, deterministic)
}
func (m *Game) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game.Merge(m, src)
}
func (m *Game) XXX_Size() int {
	return xxx_messageInfo_Game.Size(m)
}
func (m *Game) XXX_DiscardUnknown() {
	xxx_messageInfo_Game.DiscardUnknown(m)
}

var xxx_messageInfo_Game proto.InternalMessageInfo

func (m *Game) GetGameId() string {
	if m != nil {
		return m.GameId
	}
	return ""
}

func (m *Game) GetAnswer() int32 {
	if m != nil {
		return m.Answer
	}
	return 0
}

func (m *Game) GetEnded() bool {
	if m != nil {
		return m.Ended
	}
	return false
}

func (m *Game) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *Game) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *Game) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

type GameState struct {
	Game                 []*Game  `protobuf:"bytes,1,rep,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameState) Reset()         { *m = GameState{} }
func (m *GameState) String() string { return proto.CompactTextString(m) }
func (*GameState) ProtoMessage()    {}
func (*GameState) Descriptor() ([]byte, []int) {
	return fileDescriptor_d764e6f5f232c7bd, []int{3}
}

func (m *GameState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameState.Unmarshal(m, b)
}
func (m *GameState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameState.Marshal(b, m, deterministic)
}
func (m *GameState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameState.Merge(m, src)
}
func (m *GameState) XXX_Size() int {
	return xxx_messageInfo_GameState.Size(m)
}
func (m *GameState) XXX_DiscardUnknown() {
	xxx_messageInfo_GameState.DiscardUnknown(m)
}

var xxx_messageInfo_GameState proto.InternalMessageInfo

func (m *GameState) GetGame() []*Game {
	if m != nil {
		return m.Game
	}
	return nil
}

func init() {
	proto.RegisterEnum("higherlower.GuessResponse_Result", GuessResponse_Result_name, GuessResponse_Result_value)
	proto.RegisterType((*GuessRequest)(nil), "higherlower.GuessRequest")
	proto.RegisterType((*GuessResponse)(nil), "higherlower.GuessResponse")
	proto.RegisterType((*Game)(nil), "higherlower.Game")
	proto.RegisterType((*GameState)(nil), "higherlower.GameState")
}

func init() {
	proto.RegisterFile("higherlower/higherLower.proto", fileDescriptor_d764e6f5f232c7bd)
}

var fileDescriptor_d764e6f5f232c7bd = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x75, 0x9b, 0x26, 0xda, 0x69, 0xd5, 0xb8, 0x48, 0x09, 0x82, 0x50, 0x83, 0x42, 0x4f, 0x11,
	0xe2, 0xc9, 0x8b, 0x97, 0x36, 0xa6, 0x81, 0x62, 0x75, 0xda, 0xe2, 0x51, 0x56, 0x3a, 0xb4, 0x85,
	0x26, 0xa9, 0xd9, 0x84, 0xf6, 0x13, 0x3c, 0xfa, 0xc9, 0xb2, 0x9b, 0x40, 0x5b, 0xc4, 0xdb, 0xbc,
	0xb7, 0x6f, 0x1e, 0xef, 0xed, 0xc0, 0xf5, 0x62, 0x39, 0x5f, 0x50, 0xb6, 0x4a, 0x37, 0x94, 0xdd,
	0x97, 0xf3, 0x50, 0xcd, 0xde, 0x3a, 0x4b, 0xf3, 0x94, 0x37, 0xf7, 0x9e, 0xdd, 0x5b, 0x68, 0x85,
	0x05, 0x49, 0x89, 0xf4, 0x55, 0x90, 0xcc, 0xf9, 0x25, 0x98, 0x73, 0x85, 0x1d, 0xd6, 0x61, 0x5d,
	0x13, 0x4b, 0xe0, 0xfe, 0x30, 0x38, 0xad, 0x64, 0x72, 0x9d, 0x26, 0x92, 0xf8, 0x23, 0x58, 0x19,
	0xc9, 0x62, 0x95, 0x6b, 0xe1, 0x99, 0x7f, 0xe3, 0xed, 0xb9, 0x7a, 0x07, 0x5a, 0x0f, 0xb5, 0x10,
	0xab, 0x05, 0xb7, 0x0f, 0x56, 0xc9, 0xf0, 0x36, 0x70, 0x0c, 0xc6, 0xd3, 0xe1, 0xe4, 0x63, 0xfa,
	0x32, 0x7e, 0x0d, 0x7a, 0xd1, 0x73, 0x14, 0xf4, 0xed, 0x23, 0x0e, 0x60, 0x0d, 0xa2, 0x70, 0x10,
	0xa0, 0xcd, 0x78, 0x03, 0xcc, 0xe1, 0xe8, 0x3d, 0x40, 0xbb, 0xc6, 0x9b, 0x70, 0xdc, 0x1b, 0x21,
	0x06, 0xbd, 0x89, 0x6d, 0xb8, 0xdf, 0x0c, 0xea, 0xa1, 0x88, 0x89, 0xb7, 0xc1, 0x9a, 0x8b, 0x98,
	0xa2, 0x99, 0x4e, 0xd2, 0xc0, 0x0a, 0x29, 0x5e, 0x24, 0x72, 0x43, 0x99, 0x53, 0xd3, 0x55, 0x2a,
	0xa4, 0x1a, 0x52, 0x32, 0xa3, 0x99, 0x63, 0x74, 0x58, 0xf7, 0x04, 0x4b, 0xa0, 0xd4, 0x55, 0x9f,
	0x7a, 0xe9, 0x52, 0x22, 0x6e, 0x83, 0x11, 0x2f, 0x13, 0xc7, 0xd4, 0x16, 0x6a, 0xd4, 0x8c, 0xd8,
	0x3a, 0x56, 0xc5, 0x88, 0xad, 0xeb, 0x43, 0x43, 0x25, 0x19, 0xe7, 0x22, 0x27, 0x7e, 0x07, 0x75,
	0x15, 0xc0, 0x61, 0x1d, 0xa3, 0xdb, 0xf4, 0x2f, 0x0e, 0xbf, 0x45, 0xc4, 0x84, 0xfa, 0xd9, 0x7f,
	0x83, 0xf3, 0xc1, 0xee, 0x32, 0xba, 0xc8, 0x13, 0xb4, 0x42, 0xca, 0x77, 0x4e, 0xed, 0x3f, 0xbb,
	0x9a, 0xbf, 0xfa, 0x87, 0xff, 0xb4, 0xf4, 0x79, 0x1f, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc6,
	0xb3, 0x44, 0x86, 0xff, 0x01, 0x00, 0x00,
}
